Fix compatability variable naming
dask/dask pull request #10424
Opened 2023-07-21 11:58 UTC by hendrikmakait

The abbreviation **gt** is commonly used for **greater than (>)**, whereas **greater than or equal (>=)** is commonly abbreviated as **ge**. Libraries following this naming convention include
* Python Standard Library's `operator` (https://docs.python.org/3/library/operator.html#operator.ge)
* `pandas` (https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.ge.html)
* `numpy` (https://numpy.org/doc/stable/reference/generated/numpy.ndarray.__ge__.html)

I suggest that we follow this naming convention.

- [ ] Tests added / passed
- [ ] Passes `pre-commit run --all-files`

2023-07-21 12:04 UTC, hendrikmakait commented on dask/dataframe/_compat.py
> +PANDAS_GE_210 = PANDAS_VERSION.release >= (2, 1, 0)
Renaming these variables is the main change, the remainder just follows suit.

2023-07-24 11:07 UTC, crusaderky requested changes

2023-07-24 11:07 UTC, crusaderky commented on dask/dataframe/rolling.py
>              compat_kwargs = dict(engine=engine, engine_kwargs=engine_kwargs)
This if is now always true; please simplify

2023-07-24 11:07 UTC, crusaderky commented on dask/dataframe/tests/test_dataframe.py
> +        (_compat.PANDAS_GE_133, skipna is False, isinstance(idx, pd.DatetimeIndex))
```suggestion
        (PANDAS_GE_133, skipna is False, isinstance(idx, pd.DatetimeIndex))
```
plus import in header

2023-07-24 12:01 UTC, fjetter approved these changes
I'm fine with the renaming without the additional stuff @crusaderky asked for. The renaming is not a functional change while all the other requested changes are changes to logic, even if it is about the removal of dead code.

Given the size of the diff alone, I would recommend to do the functional changes in a follow up PR. This way the changes are dedicated commits which makes things much easier in case one needs to bisect, blame, etc.

2023-07-24 12:10 UTC, hendrikmakait commented
@crusaderky: I'll simplify the code in a follow-up as suggested by @fjetter.

2023-07-24 12:10 UTC, merged