Add unit test overview
dask/dask pull request #10769
Opened 2024-01-10 12:18 UTC by milesgranger

- [x] Part of https://github.com/dask/dask/issues/10732
- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

Mostly taken from dask/distributed with small adjustments

2024-01-10 12:18 UTC, GPUtester commented
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

2024-01-10 12:19 UTC, phofl commented
add to allowlist

2024-01-10 12:20 UTC, phofl commented
lets see if I have sufficient permissions for this

2024-01-10 18:03 UTC, crusaderky requested changes
It doesn't seem to work:

https://github.com/crusaderky/dask/pull/25
https://github.com/crusaderky/dask/pull/25/checks?check_run_id=20354061965
https://github.com/crusaderky/dask/actions/runs/7478648117/job/20354047349

> 2024-01-10 17:31:53 +0000 - publish - WARNING - Could not find any JUnit XML files for artifacts/**/*.xml

I think the issue is caused by the name collision below

2024-01-10 18:03 UTC, crusaderky commented on .github/workflows/tests.yml
> +          name: ${{ env.TEST_ID }}
Name collision with the 'upload environment file' action

2024-01-10 18:05 UTC, crusaderky commented on .github/workflows/tests.yml
> +          name: ${{ env.TEST_ID }}
```suggestion
          name: test-results-${{ env.TEST_ID }}
```

2024-01-11 07:05 UTC, milesgranger commented
Ah drats, my apologies @crusaderky I should have tested this myself. Working now: 
- https://github.com/milesgranger/dask/pull/1
- https://github.com/milesgranger/dask/actions/runs/7485268781

2024-01-11 10:07 UTC, crusaderky approved these changes
Looks good. 

ATM it's quite unusable though, because the report is flooded with failures from the dask-expr environment. Not sure if we want to spend time to omit that env for now or if we just want to wait for it to become green?

cc @fjetter @phofl

2024-01-11 10:08 UTC, merged