[WIP] Add optional pass_key argument to map_tasks
dask/dask pull request #6761
Opened 2020-10-22 03:24 UTC by rjzamora

- [ ] Tests added / passed
- [ ] Passes `black dask` / `flake8 dask`

2020-10-22 12:13 UTC, madsbk requested changes
I think this is a great feature @rjzamora but I am a bit concerned with the Blockwise implementation of the key (see my comment).

But if we can get this to work, let's make the `key` argument mandatory. All the `map_tasks()` implementations need to support it anyways.

2020-10-22 12:13 UTC, madsbk commented on dask/blockwise.py
> +                    new_indices.append((func([key], key), None))
I don't think this is strictly correct. `key` here is a literal and not a graph key. See https://github.com/dask/dask/blob/97c2f060d5ab31d831d20042e0a3e41ede3d2a64/dask/blockwise.py#L380-L382

2020-10-23 21:27 UTC, jrbourbeau commented
Is it safe to close this PR since we ended up going another direction in https://github.com/dask/distributed/pull/4178?

2020-10-23 21:31 UTC, rjzamora commented
Yeah - It is unlikely we will need this change.

2020-10-23 21:31 UTC, closed without merging