absolufy-imports - No relative - PEP8
dask/dask pull request #8796
Opened 2022-03-10 14:10 UTC by jsignell

Matches https://github.com/dask/distributed/pull/5924 
Conversation in https://github.com/dask/distributed/issues/5889

2022-03-14 15:43 UTC, crusaderky requested changes

2022-03-14 15:43 UTC, crusaderky commented on dask/order.py
> +from dask.utils_test import add, inc  # noqa: F401
Is this some legacy backwards compatibility? Could it be cleaned up?

2022-03-14 15:43 UTC, crusaderky commented on dask/threaded.py
> +from dask.utils_test import add, inc  # noqa: F401
legacy backwards compatibility? Can it be cleaned up?

2022-03-15 18:42 UTC, jsignell commented
I'm cleaning this up then going to merge.

2022-03-15 20:07 UTC, merged

2022-03-15 21:22 UTC, jsignell commented
@dask/maintenance if you see lots of conflicts it's likely to be this :grimacing: