RFC: Use default_client before get_client when getting the scheduler
dask/dask pull request #9723
Opened 2022-12-07 01:29 UTC by mrocklin

See https://github.com/dask/distributed/issues/7377

2022-12-07 17:14 UTC, jrbourbeau reviewed
Thanks @mrocklin! Is this something we can add a test for? Clearly our current test suite isn't capturing the many-client-in-many-threads issues you ran into

Also, in https://github.com/dask/distributed/issues/7377 you mentioned `Client.current()` is using `ContextVars` and might be a better way to go. Should we be using `Client.current()` here instead?

2022-12-14 13:11 UTC, fjetter approved these changes

2022-12-14 13:12 UTC, fjetter commented
> Also, in https://github.com/dask/distributed/issues/7377 you mentioned Client.current() is using ContextVars and might be a better way to go. Should we be using Client.current() here instead?

With https://github.com/dask/distributed/issues/7377 `Client.current` and `default_client` becomes the same thing. default_client chooses current first and then picks a global default. current falls back to global default if there is no current.

2022-12-14 13:15 UTC, fjetter requested changes

2022-12-14 13:15 UTC, fjetter commented on dask/base.py
> +                    return get_client().get
get_client will actually use the default client by default

get_clients resolution is

1. If we are a worker, select the worker and call Worker._get_client
2. Worker._get_client tries to get a default client first https://github.com/dask/distributed/blob/19deee3b1ac7298dd6b7319481417b0b4e1986d8/distributed/worker.py#L2530-L2534
3. If a ValueError is raised, it instantiates a new one.

This try/except should not be necessary and default_client should directly do the right thing, even without https://github.com/dask/distributed/issues/7377

2022-12-14 17:24 UTC, jrbourbeau reviewed
Thanks for the extra context @fjetter. Just pushed a commit to make this PR just swap out `get_client()` for `default_client()`

2022-12-15 12:55 UTC, fjetter commented
> Thanks for the extra context @fjetter. Just pushed a commit to make this PR just swap out get_client() for default_client()

No, I think we need `get_client` here, i.e. I suggest to simply close this PR and think `main` is as good as it gets.

Specifically, `get_client` will be able to open and create a client if the task is running on a worker and there is no default client registered, yet. 
`default_client` will just raise if there is no other

Effectively

`get_client` > `default_client == Client.current`

2022-12-15 12:56 UTC, fjetter commented
Practically, it won't matter much. This code branch is typically triggered because somebody set a default client. Still, get_client should "always" work and defaults to the default_client anyhow

2022-12-15 13:56 UTC, closed without merging